package designpatterns

type Pattern struct {
	ID       int
	Slug     string
	Name     string
	Category string
	Intent   string
	UseWhen  string
}

var PatternCategories = []string{"Creational", "Structural", "Behavioral"}

var Patterns = []Pattern{
	{
		ID:       1,
		Slug:     "singleton",
		Name:     "Singleton",
		Category: "Creational",
		Intent:   "Ensure a class has only one instance and provide a global access point.",
		UseWhen:  "You need shared state/configuration with controlled access.",
	},
	{
		ID:       2,
		Slug:     "factory-method",
		Name:     "Factory Method",
		Category: "Creational",
		Intent:   "Define an interface for creating an object, but let subclasses decide which class to instantiate.",
		UseWhen:  "Creation logic varies by context and you want to avoid tight coupling to concrete classes.",
	},
	{
		ID:       3,
		Slug:     "abstract-factory",
		Name:     "Abstract Factory",
		Category: "Creational",
		Intent:   "Provide an interface for creating families of related/dependent objects.",
		UseWhen:  "You must enforce compatible product variants (for example, light/dark UI kits).",
	},
	{
		ID:       4,
		Slug:     "builder",
		Name:     "Builder",
		Category: "Creational",
		Intent:   "Separate the construction of a complex object from its representation.",
		UseWhen:  "Objects have many optional fields/steps and telescoping constructors become messy.",
	},
	{
		ID:       5,
		Slug:     "prototype",
		Name:     "Prototype",
		Category: "Creational",
		Intent:   "Create new objects by cloning an existing instance.",
		UseWhen:  "Object setup is expensive and many similar objects are required.",
	},
	{
		ID:       6,
		Slug:     "adapter",
		Name:     "Adapter",
		Category: "Structural",
		Intent:   "Convert one interface into another clients expect.",
		UseWhen:  "You need to integrate incompatible interfaces without changing source code.",
	},
	{
		ID:       7,
		Slug:     "bridge",
		Name:     "Bridge",
		Category: "Structural",
		Intent:   "Decouple abstraction from implementation so both can vary independently.",
		UseWhen:  "You want to avoid class explosion from combining dimensions (shape x renderer, etc.).",
	},
	{
		ID:       8,
		Slug:     "composite",
		Name:     "Composite",
		Category: "Structural",
		Intent:   "Compose objects into tree structures and treat part-whole uniformly.",
		UseWhen:  "You model hierarchies (file systems, UI trees, org charts).",
	},
	{
		ID:       9,
		Slug:     "decorator",
		Name:     "Decorator",
		Category: "Structural",
		Intent:   "Add behavior to objects dynamically by wrapping them.",
		UseWhen:  "You need optional, combinable features without many subclasses.",
	},
	{
		ID:       10,
		Slug:     "facade",
		Name:     "Facade",
		Category: "Structural",
		Intent:   "Provide a simplified interface to a complex subsystem.",
		UseWhen:  "You want to hide subsystem complexity behind a stable API.",
	},
	{
		ID:       11,
		Slug:     "flyweight",
		Name:     "Flyweight",
		Category: "Structural",
		Intent:   "Share intrinsic state across many fine-grained objects to reduce memory.",
		UseWhen:  "Large numbers of similar objects exist (characters, map tiles, particles).",
	},
	{
		ID:       12,
		Slug:     "proxy",
		Name:     "Proxy",
		Category: "Structural",
		Intent:   "Provide a surrogate/placeholder to control access to another object.",
		UseWhen:  "You need lazy loading, access control, caching, or remote indirection.",
	},
	{
		ID:       13,
		Slug:     "chain-of-responsibility",
		Name:     "Chain of Responsibility",
		Category: "Behavioral",
		Intent:   "Pass requests along a chain until one handler processes it.",
		UseWhen:  "Multiple handlers may process a request and sender should not know receiver.",
	},
	{
		ID:       14,
		Slug:     "command",
		Name:     "Command",
		Category: "Behavioral",
		Intent:   "Encapsulate a request as an object.",
		UseWhen:  "You need undo/redo, queueing, logging, or macro operations.",
	},
	{
		ID:       15,
		Slug:     "interpreter",
		Name:     "Interpreter",
		Category: "Behavioral",
		Intent:   "Define grammar and interpreter for a small language.",
		UseWhen:  "You need to evaluate domain-specific expressions.",
	},
	{
		ID:       16,
		Slug:     "iterator",
		Name:     "Iterator",
		Category: "Behavioral",
		Intent:   "Access elements of an aggregate sequentially without exposing internals.",
		UseWhen:  "You need uniform traversal over different collections.",
	},
	{
		ID:       17,
		Slug:     "mediator",
		Name:     "Mediator",
		Category: "Behavioral",
		Intent:   "Encapsulate how objects interact to reduce direct coupling.",
		UseWhen:  "Many-to-many object communication becomes hard to maintain.",
	},
	{
		ID:       18,
		Slug:     "memento",
		Name:     "Memento",
		Category: "Behavioral",
		Intent:   "Capture and restore an object's internal state without violating encapsulation.",
		UseWhen:  "You need snapshots/checkpoints (undo history, rollback).",
	},
	{
		ID:       19,
		Slug:     "observer",
		Name:     "Observer",
		Category: "Behavioral",
		Intent:   "Define one-to-many dependency so observers are notified of state changes.",
		UseWhen:  "Event-driven updates are needed (UI updates, pub/sub).",
	},
	{
		ID:       20,
		Slug:     "state",
		Name:     "State",
		Category: "Behavioral",
		Intent:   "Let an object alter behavior when its internal state changes.",
		UseWhen:  "Behavior branches heavily on state and conditionals become large.",
	},
	{
		ID:       21,
		Slug:     "strategy",
		Name:     "Strategy",
		Category: "Behavioral",
		Intent:   "Define a family of algorithms, encapsulate each, and make them interchangeable.",
		UseWhen:  "You need runtime selection of behavior (sorting, pricing, validation rules).",
	},
	{
		ID:       22,
		Slug:     "template-method",
		Name:     "Template Method",
		Category: "Behavioral",
		Intent:   "Define algorithm skeleton in a base class and defer steps to subclasses.",
		UseWhen:  "Workflows are similar but some steps differ by variant.",
	},
	{
		ID:       23,
		Slug:     "visitor",
		Name:     "Visitor",
		Category: "Behavioral",
		Intent:   "Separate operations from object structure by moving behavior into visitor objects.",
		UseWhen:  "You frequently add operations over a stable object structure.",
	},
}
