name: Packages NuGet

permissions:
  contents: read

on:
  push:
    branches: [main]
  pull_request:
    paths:
      - packages/nuget/**
      - .github/workflows/packages-nuget.yml

defaults:
  run:
    working-directory: packages/nuget

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - run: dotnet build
      - run: dotnet test
